## USB port
port: /dev/ttyACM3


##### Calibration ####
### accelerometer
accel_x_min: -280.0
accel_x_max: 265.0
accel_y_min: -280.0
accel_y_max: 287.0
accel_z_min: -290.0
accel_z_max: 250.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [120.542, -540.627, -587.313]
magn_ellipsoid_transform: [[0.974820, 0.000661577, 0.0178611], [0.000661577, 0.997249, -0.00322917], [0.0178611, -0.00322917, 0.984544]]


# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -0.03
gyro_average_offset_y: -0.01
gyro_average_offset_z: -0.025
